### ISSUE TITLE
Notification Token do not get reset on logout

### ISSUE THREAD

**Issue by seandkim** [comewithgeul/comewithgeul#100]
Looking at the database, the notification Token does not get reset on logout. Because of this, the logged out user will continue to receive a notification which is wrong.

**Comment by afkim14** [comment]
Nice catch. Will change it. Two questions:

1. What about when a JWT expires? Do you automatically set the notificationToken of that user to null?
2. Do you set the notificationToken of the user to null when they delete their account"?

In the two scenarios above, the user won't be logged in (authenticated) so I can't update the user's notificationToken.

**Comment by afkim14** [comment]
Also, the [PUT user/me endpoint](https://docs.google.com/document/d/1FFK05tAq7rh8tAFQawcaEkQ9klv5V937jFISSoPkjkM/edit#heading=h.ag1v6jeief3p) is giving me a 401 with message "Logged in user is different from the user in the request body" unless I specify the `userId` in the body.

**Comment by seandkim** [comment]
1. Expiration of JWT token should not affect the notification token. From user perspective, they should receive notification even if they haven't logged in for a while. (Also, before we set & enforce expiration time on the access token, the backend should issue a refresh token so that the frontend can keep issuing the access token; this work is pending)
2. `User` entity is hard deleted and `DeleteUser` entity is created

**Comment by seandkim** [comment]
3. On PUT user/me endpoint, I do specify `Id` not `UserId`... See [this code](https://github.com/comewithgeul/comewithgeul/blob/3f65fc1322265891844c5c56d39bf31a1c3e061d/hallasan/src/Service/Controllers/v2/UserControllerV2.cs#L61)

**Comment by afkim14** [comment]
> 1. Expiration of JWT token should not affect the notification token. From user perspective, they should receive notification even if they haven't logged in for a while. (Also, before we set & enforce expiration time on the access token, the backend should issue a refresh token so that the frontend can keep issuing the access token; this work is pending)
> 2. `User` entity is hard deleted and `DeleteUser` entity is created

If the JWT token expires, they'll be asked to re-login when they open the app. Isn't it incorrect for them to receive notifications then? Shouldn't you check for when you get a JWT expired exception and unset the user's notification token?

Agreed on the refresh token.

**Comment by afkim14** [comment]
> 1. On PUT user/me endpoint, I do specify `Id` not `UserId`... See [this code](https://github.com/comewithgeul/comewithgeul/blob/3f65fc1322265891844c5c56d39bf31a1c3e061d/hallasan/src/Service/Controllers/v2/UserControllerV2.cs#L61)

Sorry, I meant `id`. Why do we have to specify `id` here if it's a /me endpoint?

**Comment by seandkim** [comment]
3. Yes, to make the API restful. Response of GET /me and request body of PUT /me should have the same schema

**Comment by seandkim** [comment]
1. Good point. We should set notification token to null on when backend raises jwt expired exception. Note that this is different from when jwt token actually expire

**Comment by afkim14** [comment]
Notification token now gets reset on logout. Related commit: 8cd0c5b28e466cdc8167fb533d7c66ec53fd46cf
