### ISSUE TITLE
The width of the selected table icon does not match

### ISSUE THREAD

**Issue by bykbyk301** [comewithgeul/comewithgeul#101]
It's because the uploaded icon in zeplin had a wrong size. I re uploaded the correct version.

- unselected icon is correct!
- please just replace the *selected* icon with the new one in zeplin.

 ![image](https://user-images.githubusercontent.com/16695846/107850564-a4685880-6e46-11eb-8e49-1fc5afec8b26.png)

**Comment by afkim14** [comment]
Could we make the selected and the not selected icons the same size? On zeplin the selected one is 17pt x 12pt, and the not selected one is 19pt x 16pt

**Comment by bykbyk301** [comment]
🤦🏻‍♀️ It should be the same now!

**Comment by afkim14** [comment]
Updated! Relevant commit: https://github.com/comewithgeul/comewithgeul/commit/7b0d5c4fdf51bc1797d3ca09d03e7d9f6f446d1a
