### ISSUE TITLE
Posting a comment sometimes fail

### ISSUE THREAD

**Issue by seandkim** [comewithgeul/comewithgeul#103]
https://user-images.githubusercontent.com/20718126/107905532-b6f49780-6f03-11eb-8d8c-43c8fde73f63.MP4

**Comment by seandkim** [comment]
The editor posted announcement feedback three times and one participant posted once; for some reason I don't see any log on the editor's announcement feedback. 

![image](https://user-images.githubusercontent.com/20718126/107907785-74ce5480-6f09-11eb-952b-38a90df04633.png)

**Comment by seandkim** [comment]
@afkim14 Can you reproduce this & check if the call is reaching the backend?

**Comment by afkim14** [comment]
Issue fixed in this PR: https://github.com/comewithgeul/comewithgeul/pull/112
