### ISSUE TITLE
Wrong duplicate highlight on search

### ISSUE THREAD

**Issue by seandkim** [comewithgeul/comewithgeul#113]
When the highlight matches the author, it highlights the title as well which is wrong

![image](https://user-images.githubusercontent.com/20718126/111494154-95483380-8781-11eb-8d72-7239252ff9ac.png)

**Comment by afkim14** [comment]
Ahhhhhhhhhhhhhh!

**Comment by afkim14** [comment]
Issue fixed in this commit: https://github.com/comewithgeul/comewithgeul/commit/fc3f2e987671d54747097c845a60810901a63360 (not yet deployed)
