### ISSUE TITLE
테이블 입장하기 버튼

### ISSUE THREAD

**Issue by bykbyk301** [comewithgeul/comewithgeul#115]
![image](https://user-images.githubusercontent.com/16695846/111937226-a0e18480-8b0a-11eb-8d84-c5ac9008d7f5.png)

The Y position of the buttons on this page are consistenly off

**Comment by afkim14** [comment]
@bykbyk301 This looks like an old version. The text should not be that close to the keyboard in the newest version. Could you try reloading?
