### ISSUE TITLE
Listing rooms of a user is slow

### ISSUE THREAD

**Issue by seandkim** [comewithgeul/comewithgeul#8]
In expo, "list rooms of a user view" is very slow.

**Comment by afkim14** [comment]
This issue seems to have been mitigated with the new ["GetMostRecent" endpoint](https://docs.google.com/document/d/1FFK05tAq7rh8tAFQawcaEkQ9klv5V937jFISSoPkjkM/edit#heading=h.m6eqn53ofua4).
