### ISSUE TITLE
탈퇴한 사용자 in historical room

### ISSUE THREAD

**Issue by bykbyk301** [comewithgeul/comewithgeul#95]
![image](https://user-images.githubusercontent.com/16695846/107349351-75cb4480-6b0b-11eb-903c-db5ebe5323ac.png)

The historical room view is still counting 탈퇴한 사용자

**Comment by afkim14** [comment]
My assumption was that since we're still displaying the 탈퇴한 사용자 user filter and undeleted writings, I still counted them in the total number of participants. Do you think that's weird? I think if we want to remove them from the count, we should also remove them from the writing section below.

**Comment by seandkim** [comment]
I vote for including the deleted user

**Comment by bykbyk301** [comment]
That makes sense. I was initially thrown off because the table profile view was showing three nicknames only and in the historical view it was suddenly counting four. We can close this issue.

**Comment by afkim14** [comment]
What do you think about displaying 탈퇴한 사용자  in a lighter color under the list of participants in the room info view? I can sort it so 탈퇴한 사용자s are always at the bottom

**Comment by seandkim** [comment]
I like it

**Comment by afkim14** [comment]
Like this @bykbyk301 :

![IMG_3305](https://user-images.githubusercontent.com/14881100/107708788-19466180-6c92-11eb-99dc-7e2d9990f13d.PNG)

**Comment by bykbyk301** [comment]
I like it!!

**Comment by afkim14** [comment]
Updated with this commit: 9d0c6063da73a81ed4f48146e103812fb9ed820f
